#!/usr/bin/env python3
"""Clone the licitaciones Supabase schema into a fresh (UTE) project.

The schema source of truth is the source project's applied migration history
(`supabase_migrations.schema_migrations`). The exact statements that built the
production DB are replayed into the target, element by element, in version
order, and the bookkeeping rows are copied so the UTE project starts at the
same migration HEAD. Future migrations (via MCP `apply_migration`) then append
cleanly to both projects.

Production data is NEVER copied. Only reference/catalog tables are seeded.

Connections are Postgres URIs. In Supabase: Project Settings -> Database ->
Connection string -> URI (use the Session pooler). Pass them via env:

    export SOURCE_DB_URL='postgresql://postgres.<ref>:<pwd>@<host>:5432/postgres?sslmode=require'
    export TARGET_DB_URL='postgresql://postgres.<ute-ref>:<pwd>@<host>:5432/postgres?sslmode=require'

Commands:
    python clone_ute.py dump   [--out ./out]   # SOURCE -> schema.sql + migrations.json
    python clone_ute.py apply  [--in ./out] [--dry-run]  # migrations -> TARGET (idempotent)
    python clone_ute.py seed   [--truncate]    # SOURCE -> TARGET reference tables
    python clone_ute.py verify                 # inventory diff SOURCE vs TARGET

`apply` reads migrations from <in>/migrations.json if present, otherwise live
from SOURCE_DB_URL. It is idempotent: versions already in the target are skipped.

Requires: psycopg2 (see requirements.txt).
"""
import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

# Reference/catalog tables seeded into UTE. Everything else starts empty.
REFERENCE_TABLES = [
    "app_settings",
    "ai_pricing",
    "model_tiers",
    "service_prompts",
    "tender_evaluation_types",
]

INVENTORY_SQL = """
select 'tables' as kind, count(*)::int as n from information_schema.tables where table_schema='public' and table_type='BASE TABLE'
union all select 'views', count(*)::int from information_schema.views where table_schema='public'
union all select 'enums', count(distinct t.typname)::int from pg_type t join pg_enum e on e.enumtypid=t.oid join pg_namespace n on n.oid=t.typnamespace where n.nspname='public'
union all select 'functions', count(*)::int from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'
union all select 'triggers', count(*)::int from information_schema.triggers where trigger_schema='public'
union all select 'rls_policies', count(*)::int from pg_policies where schemaname='public'
union all select 'sequences', count(*)::int from information_schema.sequences where sequence_schema='public'
union all select 'migrations', count(*)::int from supabase_migrations.schema_migrations
order by kind;
"""

MIGRATIONS_BOOTSTRAP = """
create schema if not exists supabase_migrations;
create table if not exists supabase_migrations.schema_migrations (
    version text primary key,
    statements text[],
    name text
);
"""


def connect(env_var):
    import psycopg2
    url = os.environ.get(env_var)
    if not url:
        sys.exit(f"error: {env_var} is not set (see header of this file)")
    conn = psycopg2.connect(url)
    return conn


def fetch_migrations(conn):
    with conn.cursor() as cur:
        cur.execute(
            "select version, name, statements "
            "from supabase_migrations.schema_migrations order by version;"
        )
        return [
            {"version": v, "name": n, "statements": list(s or [])}
            for v, n, s in cur.fetchall()
        ]


# --------------------------------------------------------------------------- #
# dump
# --------------------------------------------------------------------------- #
def cmd_dump(args):
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    conn = connect("SOURCE_DB_URL")
    try:
        migrations = fetch_migrations(conn)
    finally:
        conn.close()

    (out / "migrations.json").write_text(
        json.dumps(migrations, ensure_ascii=False, indent=2)
    )

    now = datetime.now(timezone.utc).isoformat()
    lines = [
        f"-- Generated by clone_ute.py dump on {now}",
        f"-- {len(migrations)} migrations replayed in version order.",
        "-- Authoritative apply path is `clone_ute.py apply` (executes each",
        "-- statement element exactly as originally applied). This .sql is a",
        "-- human-readable concatenation for review / manual psql apply.",
        "",
    ]
    for m in migrations:
        lines.append(f"-- >>> migration {m['version']}  {m['name']}")
        for stmt in m["statements"]:
            stmt = stmt.strip()
            if not stmt:
                continue
            if not stmt.endswith(";"):
                stmt += ";"
            lines.append(stmt)
        lines.append(f"-- <<< end {m['version']}")
        lines.append("")
    (out / "schema.sql").write_text("\n".join(lines))

    print(f"dumped {len(migrations)} migrations -> {out}/migrations.json, {out}/schema.sql")


# --------------------------------------------------------------------------- #
# apply
# --------------------------------------------------------------------------- #
def load_migrations_for_apply(args):
    manifest = Path(args.in_dir) / "migrations.json"
    if manifest.exists():
        print(f"loading migrations from {manifest}")
        return json.loads(manifest.read_text())
    print("no migrations.json found; reading live from SOURCE_DB_URL")
    conn = connect("SOURCE_DB_URL")
    try:
        return fetch_migrations(conn)
    finally:
        conn.close()


def cmd_apply(args):
    migrations = load_migrations_for_apply(args)
    target = connect("TARGET_DB_URL")
    target.autocommit = False
    try:
        with target.cursor() as cur:
            cur.execute(MIGRATIONS_BOOTSTRAP)
            cur.execute("select version from supabase_migrations.schema_migrations;")
            already = {r[0] for r in cur.fetchall()}
        target.commit()

        applied, skipped = 0, 0
        for m in sorted(migrations, key=lambda x: x["version"]):
            if m["version"] in already:
                skipped += 1
                continue
            if args.dry_run:
                print(f"  would apply {m['version']}  {m['name']} "
                      f"({len(m['statements'])} stmts)")
                applied += 1
                continue
            try:
                with target.cursor() as cur:
                    for stmt in m["statements"]:
                        if stmt and stmt.strip():
                            cur.execute(stmt)
                    cur.execute(
                        "insert into supabase_migrations.schema_migrations "
                        "(version, name, statements) values (%s, %s, %s) "
                        "on conflict (version) do nothing;",
                        (m["version"], m["name"], m["statements"]),
                    )
                target.commit()
                applied += 1
                print(f"  applied  {m['version']}  {m['name']}")
            except Exception as exc:
                target.rollback()
                sys.exit(f"FAILED at {m['version']} {m['name']}: {exc}")
        verb = "would apply" if args.dry_run else "applied"
        print(f"{verb} {applied}, skipped {skipped} (already present)")
    finally:
        target.close()


# --------------------------------------------------------------------------- #
# seed
# --------------------------------------------------------------------------- #
def pk_columns(conn, table):
    with conn.cursor() as cur:
        cur.execute(
            "select a.attname from pg_index i "
            "join pg_attribute a on a.attrelid=i.indrelid and a.attnum = any(i.indkey) "
            "where i.indrelid = %s::regclass and i.indisprimary "
            "order by array_position(i.indkey, a.attnum);",
            (f"public.{table}",),
        )
        return [r[0] for r in cur.fetchall()]


def column_types(conn, table):
    with conn.cursor() as cur:
        cur.execute(
            "select column_name, data_type from information_schema.columns "
            "where table_schema='public' and table_name=%s order by ordinal_position;",
            (table,),
        )
        return {name: dtype for name, dtype in cur.fetchall()}


def adapt(value, dtype):
    # jsonb/json come back as dict/list and must be re-wrapped; arrays pass through.
    if value is not None and dtype in ("jsonb", "json"):
        import psycopg2.extras
        return psycopg2.extras.Json(value)
    return value


def cmd_seed(args):
    source = connect("SOURCE_DB_URL")
    target = connect("TARGET_DB_URL")
    target.autocommit = False
    try:
        for table in REFERENCE_TABLES:
            pks = pk_columns(target, table)
            if not pks:
                sys.exit(f"no primary key found on public.{table}; cannot upsert")
            types = column_types(target, table)
            cols = list(types.keys())

            with source.cursor() as cur:
                cur.execute(f'select {", ".join(cols)} from public.{table};')
                rows = cur.fetchall()

            if args.truncate:
                with target.cursor() as cur:
                    cur.execute(f"truncate public.{table} cascade;")

            non_pk = [c for c in cols if c not in pks]
            placeholders = ", ".join(["%s"] * len(cols))
            set_clause = ", ".join(f"{c}=excluded.{c}" for c in non_pk) or \
                f"{pks[0]}=excluded.{pks[0]}"
            sql = (
                f'insert into public.{table} ({", ".join(cols)}) '
                f"values ({placeholders}) "
                f'on conflict ({", ".join(pks)}) do update set {set_clause};'
            )
            with target.cursor() as cur:
                for row in rows:
                    cur.execute(sql, [adapt(v, types[c]) for c, v in zip(cols, row)])
            target.commit()
            print(f"  seeded {len(rows):>4} rows -> public.{table}")
        print("reference seed complete (no production data copied)")
    finally:
        source.close()
        target.close()


# --------------------------------------------------------------------------- #
# verify
# --------------------------------------------------------------------------- #
def inventory(conn):
    with conn.cursor() as cur:
        cur.execute(INVENTORY_SQL)
        return dict(cur.fetchall())


def cmd_verify(args):
    source = connect("SOURCE_DB_URL")
    target = connect("TARGET_DB_URL")
    try:
        src, tgt = inventory(source), inventory(target)
    finally:
        source.close()
        target.close()

    kinds = sorted(set(src) | set(tgt))
    print(f"{'kind':<16}{'source':>8}{'target':>8}  diff")
    ok = True
    for k in kinds:
        s, t = src.get(k, 0), tgt.get(k, 0)
        flag = "" if s == t else "  <-- MISMATCH"
        if s != t:
            ok = False
        print(f"{k:<16}{s:>8}{t:>8}{flag}")
    print("\nOK: schemas match" if ok else "\nMISMATCH: see rows above")
    sys.exit(0 if ok else 1)


def main():
    parser = argparse.ArgumentParser(description="Clone licitaciones schema into a UTE project")
    sub = parser.add_subparsers(dest="command", required=True)

    p_dump = sub.add_parser("dump", help="SOURCE -> schema.sql + migrations.json")
    p_dump.add_argument("--out", default="./out")
    p_dump.set_defaults(func=cmd_dump)

    p_apply = sub.add_parser("apply", help="migrations -> TARGET (idempotent)")
    p_apply.add_argument("--in", dest="in_dir", default="./out")
    p_apply.add_argument("--dry-run", action="store_true")
    p_apply.set_defaults(func=cmd_apply)

    p_seed = sub.add_parser("seed", help="SOURCE -> TARGET reference tables")
    p_seed.add_argument("--truncate", action="store_true",
                        help="truncate each reference table before insert")
    p_seed.set_defaults(func=cmd_seed)

    p_verify = sub.add_parser("verify", help="inventory diff SOURCE vs TARGET")
    p_verify.set_defaults(func=cmd_verify)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
