trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: main-vars

strategy:
  matrix:
    service-file-extractor:
      SERVICE_NAME: "service-file-extractor"
    # service-files-converter:
    #   SERVICE_NAME: "service-files-converter"
    # service-chunk-and-index:
    #   SERVICE_NAME: "service-chunk-and-index"
    # service-setup-qdrant:
    #   SERVICE_NAME: "service-setup-qdrant"
    # service-iterative-requirement-extractor:
    #   SERVICE_NAME: "service-iterative-requirement-extractor"
    # service-verify-compliance:
    #   SERVICE_NAME: "service-verify-compliance"

steps:
  - script: |
      echo "$REGISTRY_PASS" | docker login "$REGISTRY_SERVER" \
        -u "$REGISTRY_USER" \
        --password-stdin
    displayName: "Login to ACR"
    env:
      REGISTRY_SERVER: $(AZURE_REGISTRY_SERVER)
      REGISTRY_USER: $(AZURE_REGISTRY_USER)
      REGISTRY_PASS: $(AZURE_REGISTRY_PASS)

  - script: |
      cd $(SERVICE_NAME)
      chmod +x azure-build-and-push.sh
      ./azure-build-and-push.sh
    displayName: "Build & Push $(SERVICE_NAME)"
