trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: othes-vars
  - group: api-vars
  - group: supabase-vars

strategy:
  matrix:
    service-file-extractor:
      SERVICE_NAME: "service-file-extractor"
    service-files-converter:
      SERVICE_NAME: "service-files-converter"
    service-setup-qdrant:
      SERVICE_NAME: "service-setup-qdrant"
    service-chunk-and-index:
      SERVICE_NAME: "service-chunk-and-index"
    service-requirement-extractor:
      SERVICE_NAME: "service-requirement-extractor"
    service-verify-compliance:
      SERVICE_NAME: "service-verify-compliance"
    service-metadata-extractor:
      SERVICE_NAME: "service-metadata-extractor"
    service-proposal-scorer:
      SERVICE_NAME: "service-proposal-scorer"
    service-qdrant-by-file:
      SERVICE_NAME: "service-qdrant-by-file"
    service-file-metadata-extractor:
      SERVICE_NAME: "service-file-metadata-extractor"
    service-documents-clasification:
      SERVICE_NAME: "service-documents-clasification"

steps:
  - script: |
      echo "$REGISTRY_PASS" | docker login "$REGISTRY_SERVER" \
        -u "$REGISTRY_USER" \
        --password-stdin
    displayName: "Login to ACR"
    env:
      REGISTRY_SERVER: $(AZURE_REGISTRY_SERVER)
      REGISTRY_USER: $(AZURE_REGISTRY_USER)
      REGISTRY_PASS: $(AZURE_REGISTRY_PASS)

  - script: |
      cd $(SERVICE_NAME)
      chmod +x build-and-push.sh
      ./build-and-push.sh azure
    displayName: "Build & Push $(SERVICE_NAME)"
    env:
      AZURE_REGISTRY_SERVER: $(AZURE_REGISTRY_SERVER)
      SUPABASE_URL: $(SUPABASE_URL)
      SUPABASE_SERVICE_KEY: $(SUPABASE_SERVICE_KEY)
      SUPABASE_ARTIFACTS_BASE_URL: $(SUPABASE_ARTIFACTS_BASE_URL)
      SUPABASE_FILES_BASE_URL: $(SUPABASE_FILES_BASE_URL)
      OPENAI_API_KEY: $(OPENAI_API_KEY)
      GOOGLE_API_KEY: $(GOOGLE_API_KEY)
      LLAMA_CLOUD_API_KEY: $(LLAMA_CLOUD_API_KEY)
      QDRANT_URL: $(QDRANT_URL)
      QDRANT_API_KEY: $(QDRANT_API_KEY)
      COHERE_API_KEY: $(COHERE_API_KEY)
      API_KEY: $(API_KEY)
      API_BASE_URL: $(API_BASE_URL)
      API_EVENTS_PATH: $(API_EVENTS_PATH)
      API_PROPOSALS_PATH: $(API_PROPOSALS_PATH)
      API_ANALYSES_PATH: $(API_ANALYSES_PATH)
      API_FILES_PATH: $(API_FILES_PATH)
      API_JOBS_CALLBACK: $(API_JOBS_CALLBACK)
      API_REQUIREMENTS_PATH: $(API_REQUIREMENTS_PATH)
      API_COMPLIANCE_RESULTS_PATH: $(API_COMPLIANCE_RESULTS_PATH)
